# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2024
customText = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="license noopener"><img alt="Creative Commons License" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" /><img alt="Attribution" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" /><img alt="NonCommercial" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" /><img alt="NoDerivs" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" /> This site is licensed under a CC BY-NC-ND 4.0 International License.</a>'

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸŒ»"
subtitle = "å—¨ï¼è¿™é‡Œæ˜¯ Kristineï¼ä¸€ä¸ªå‘æ—¥è‘µæœºå™¨äººï¼Œä¸€ä¸ªæƒ³ç”¨æ–‡å­—æ”¹å˜ä¸–ç•Œçš„äººï¼Œæ­£åœ¨è·µè¡Œå­˜åœ¨ä¸»ä¹‰çš„å¿ƒç†å­¦äººã€‚è®°å½•æ•…äº‹ï¼Œè¯ é‡Šç”Ÿå‘½ã€‚åˆ†äº«ä¸ªäººæˆé•¿ä¸æ³›å¿ƒç†å†…å®¹ï¼Œè‡´åŠ›äºæ¶ˆé™¤æ€§å°‘æ•°ä¸å¿ƒç†éšœç¢çš„æ±¡ååŒ–ï¼Œä¿ƒè¿›æ€§/åˆ«å¤šå…ƒä¸ç¥ç»å¤šæ ·æ€§çš„å¹³ç­‰ã€‚"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar-æˆ‘æ˜¯ä¸€ä¸ªå‘æ—¥è‘µæœºå™¨äºº.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-ND 4.0"

## Widgets
[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
