baseURL = 'https://SunlitCosmos.com/'
defaultContentLanguage = 'zh-cn'
theme = 'hugo-theme-stack'
summaryLength = 20
disqusShortname = 'Kristine'
googleAnalytics = 'G-MEASUREMENT_ID'

[pagination]
  pagerSize = 5

[languages]
  [languages.en]
    languageCode = 'en-us'
    title = 'Sunlit Cosmos'
    weight = 1
    [languages.en.params]
      mainSections = ['post']
      sidebar = { emoji = "ğŸŒ»", subtitle = "Hi! This is Kristine! A sunflower robot, a person who wants to change the world with words, and a psychology student practicing existentialism. Recording stories, interpreting life." }
      [[languages.en.params.widgets.page]]
        type = "toc"
      [[languages.en.params.widgets.page]]
        type = "search"
      [[languages.en.params.widgets.page]]
        type = "archives"
        [languages.en.params.widgets.page.params]
          limit = 5
      [[languages.en.params.widgets.page]]
        type = "categories"
        [languages.en.params.widgets.page.params]
          limit = 10
      [[languages.en.params.widgets.page]]
        type = "tag-cloud"
        [languages.en.params.widgets.page.params]
          limit = 10
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
        params = { icon = 'home' }
      [[languages.en.menu.main]]
        name = 'About'
        pageRef = '/page/about'
        weight = 20
        params = { icon = 'user' }
      [[languages.en.menu.main]]
        name = 'Search'
        pageRef = '/page/search'
        weight = 30
        params = { icon = 'search' }
      [[languages.en.menu.main]]
        name = 'Archives'
        pageRef = '/page/archives'
        weight = 40
        params = { icon = 'archives' }
      [[languages.en.menu.main]]
        name = 'Links'
        pageRef = '/page/links'
        weight = 50
        params = { icon = 'link' }

  [languages.zh-cn]
    languageCode = 'zh-cn'
    title = 'æ—¥æ™ä¹‹é‡ Sunlit Cosmos'
    weight = 2
    [languages.zh-cn.params]
      mainSections = ['post']
      sidebar = { emoji = "ğŸŒ»", subtitle = "å—¨ï¼è¿™é‡Œæ˜¯ Kristineï¼ä¸€ä¸ªå‘æ—¥è‘µæœºå™¨äººï¼Œä¸€ä¸ªæƒ³ç”¨æ–‡å­—æ”¹å˜ä¸–ç•Œçš„äººï¼Œæ­£åœ¨è·µè¡Œå­˜åœ¨ä¸»ä¹‰çš„å¿ƒç†å­¦äººã€‚è®°å½•æ•…äº‹ï¼Œè¯ é‡Šç”Ÿå‘½ã€‚åˆ†äº«ä¸ªäººæˆé•¿ä¸æ³›å¿ƒç†å†…å®¹ï¼Œè‡´åŠ›äºæ¶ˆé™¤æ€§å°‘æ•°ä¸å¿ƒç†éšœç¢çš„æ±¡ååŒ–ï¼Œä¿ƒè¿›æ€§/åˆ«å¤šå…ƒä¸ç¥ç»å¤šæ ·æ€§çš„å¹³ç­‰ã€‚" }
      [[languages.zh-cn.params.widgets.page]]
        type = "toc"
      [[languages.zh-cn.params.widgets.page]]
        type = "search"
      [[languages.zh-cn.params.widgets.page]]
        type = "archives"
        [languages.zh-cn.params.widgets.page.params]
          limit = 5
      [[languages.zh-cn.params.widgets.page]]
        type = "categories"
        [languages.zh-cn.params.widgets.page.params]
          limit = 10
      [[languages.zh-cn.params.widgets.page]]
        type = "tag-cloud"
        [languages.zh-cn.params.widgets.page.params]
          limit = 10
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        name = 'ä¸»é¡µ'
        pageRef = '/'
        weight = 10
        params = { icon = 'home' }
      [[languages.zh-cn.menu.main]]
        name = 'å…³äºæˆ‘'
        pageRef = '/page/about'
        weight = 20
        params = { icon = 'user' }
      [[languages.zh-cn.menu.main]]
        name = 'æœç´¢'
        pageRef = '/page/search'
        weight = 30
        params = { icon = 'search' }
      [[languages.zh-cn.menu.main]]
        name = 'æ–‡ç« å½’æ¡£'
        pageRef = '/page/archives'
        weight = 40
        params = { icon = 'archives' }
      [[languages.zh-cn.menu.main]]
        name = 'ç›¸å…³é“¾æ¥'
        pageRef = '/page/links'
        weight = 50
        params = { icon = 'link' }

[params]
  mainSections = ['post']
  rssFullContent = true
  favicon = "/sunlit robot æœºå™¨äººå¤´.png"
  
  [params.author]
    name = "Kristine Yuxi"
    email = "your-email@example.com"
    
  [params.footer]
    since = 2024
    customText = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="license noopener"><img alt="Creative Commons License" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" /><img alt="Attribution" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" /><img alt="NonCommercial" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" /><img alt="NoDerivs" style="border-width:0;vertical-align:middle;max-width:1.2em;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" /> This site is licensed under a CC BY-NC-ND 4.0 International License.</a>'
  
  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar.avatar]
      enabled = true
      local = true
      src = "assets/img/avatar-æˆ‘æ˜¯ä¸€ä¸ªå‘æ—¥è‘µæœºå™¨äºº.png"

  [params.article]
    headingAnchor = false
    math = false
    readingTime = true
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-ND 4.0"

  [params.widgets]
    [[params.widgets.homepage]]
      type = "search"
    [[params.widgets.homepage]]
      type = "archives"
      [params.widgets.homepage.params]
        limit = 5
    [[params.widgets.homepage]]
      type = "categories"
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.homepage]]
      type = "tag-cloud"
      [params.widgets.homepage.params]
        limit = 10
    [[params.widgets.page]]
      type = "toc"
	[[params.widgets.page]]
      type = "search"
    [[params.widgets.page]]
      type = "archives"
      [params.widgets.page.params]
        limit = 5
    [[params.widgets.page]]
      type = "categories"
      [params.widgets.page.params]
        limit = 10
    [[params.widgets.page]]
      type = "tag-cloud"
      [params.widgets.page.params]
        limit = 10

  [params.colorScheme]
    toggle = true
    default = "auto"
    
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = true
  [markup.highlight]
    noClasses = false

[permalinks]
  post = '/:slug/'

[related]
  includeNewer = true
  threshold = 60
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'categories'
    weight = 200